#!/bin/tcsh -f
set projectpath=/home/oleg/RTLtoGDS/projects/map9v3
set modulename=map9v3
set techname=osu035 
set techdir=/home/oleg/RTLtoGDS/tech/osu035
set sourcedir=/home/oleg/RTLtoGDS/projects/map9v3/source
set synthdir=/home/oleg/RTLtoGDS/projects/map9v3/synthesis
set layoutdir=/home/oleg/RTLtoGDS/projects/map9v3/layout
set scriptdir=/home/oleg/RTLtoGDS/scripts
set bindir=/home/oleg/RTLtoGDS/bin
set logdir=/home/oleg/RTLtoGDS/projects/map9v3/log
