#!/bin/tcsh -f
set projectpath=/home/oleg/tool_RTL_to_GDSII/projects/map9v3
set modulename=map9v3
set techname=osu035 
set techdir=/home/oleg/tool_RTL_to_GDSII/tech/osu035
set sourcedir=/home/oleg/tool_RTL_to_GDSII/projects/map9v3/source
set synthdir=/home/oleg/tool_RTL_to_GDSII/projects/map9v3/synthesis
set layoutdir=/home/oleg/tool_RTL_to_GDSII/projects/map9v3/layout
set scriptdir=/home/oleg/tool_RTL_to_GDSII/scripts
set bindir=/home/oleg/tool_RTL_to_GDSII/bin
set logdir=/home/oleg/tool_RTL_to_GDSII/projects/map9v3/log
