#!/bin/tcsh -f
set projectpath=/home/oleg/RTLtoGDS/projects/i2c
set modulename=i2c_master_top
set techname=osu035 
set techdir=/home/oleg/RTLtoGDS/tech/osu035
set sourcedir=/home/oleg/RTLtoGDS/projects/i2c/source
set synthdir=/home/oleg/RTLtoGDS/projects/i2c/synthesis
set layoutdir=/home/oleg/RTLtoGDS/projects/i2c/layout
set scriptdir=/home/oleg/RTLtoGDS/scripts
set bindir=/home/oleg/RTLtoGDS/bin
set logdir=/home/oleg/RTLtoGDS/projects/i2c/log
